# Generated by Django 4.1.5 on 2024-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('mobileno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('guests', models.DecimalField(decimal_places=2, max_digits=3)),
                ('arrivals', models.DateField()),
                ('leaving', models.DateField()),
            ],
        ),
    ]
