# Generated by Django 4.1.5 on 2024-07-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='img',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='package',
            name='pdays',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='package',
            name='pdesc',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='ptitle',
            field=models.CharField(default='', max_length=122),
        ),
    ]
