# Generated by Django 4.1.5 on 2024-07-14 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_package_img_package_pdays_package_pdesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='acco',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pdesc',
            field=models.TextField(default='', max_length=500),
        ),
    ]
