# Generated by Django 4.1.5 on 2024-07-14 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_package_acco_alter_package_img_alter_package_pdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='inc',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='meal',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='pdesc',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
