# Generated by Django 4.1.5 on 2024-07-27 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_package_inc_package_meal_alter_package_pdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='guests',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
