# Generated by Django 4.1.5 on 2024-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_book_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
