# Generated by Django 4.1.5 on 2024-07-27 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='guests',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobileno',
            field=models.CharField(max_length=15),
        ),
    ]
