# Generated by Django 4.1.5 on 2024-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_guests_alter_book_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='payment_id',
            field=models.CharField(default='default_payment_id', max_length=100),
        ),
    ]
