# Generated by Django 4.1.5 on 2024-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_book_paid_book_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_id',
            field=models.CharField(default='default_order_id', max_length=100),
        ),
    ]
