# Generated by Django 4.1.5 on 2024-07-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment_id',
        ),
    ]
