# Generated by Django 4.1.5 on 2024-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_payment_amount_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
