# Generated by Django 4.1.5 on 2024-08-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_book_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
