# Generated by Django 4.1.5 on 2024-08-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
