# Generated by Django 4.1.5 on 2024-08-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment_id',
        ),
    ]
