# Generated by Django 4.1.5 on 2024-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_book_paid_remove_book_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
