# Generated by Django 4.1.5 on 2024-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_book_paid_remove_book_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
