# Generated by Django 4.1.5 on 2024-09-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_book_payment_status_book_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
