# Generated by Django 4.1.5 on 2024-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_book_paid_book_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment_id',
        ),
    ]
