# Generated by Django 4.1.5 on 2024-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_book_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pprice',
            field=models.IntegerField(null=True),
        ),
    ]
