# Generated by Django 4.1.5 on 2024-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_book_pprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_id',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
