# Generated by Django 4.1.5 on 2024-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_book_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
